spring:
  datasource:
    master:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: replUser
      password: 1234
      jdbc-url: jdbc:mysql://host.docker.internal:13306/pet_hub?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul

    slave:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: replUser
      password: 1234
      jdbc-url: jdbc:mysql://host.docker.internal:13307/pet_hub?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
  jwt:
    secretKey: vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalwejkfjweujrhfznmxcvwerxzcv
  security:
    oauth2:
      client:
        registration:
          naver:
            client-name: naver
            client-id: wdyVDz8Boe8hbT6Oy5mT
            client-secret: GEEJgChLfT
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            scope: name,email,nickname
          google:
            client-name: google
            client-id: 537136001846-u0lbhncgb4djdkiaa3c2gadfpma3q86s.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: http://localhost:8080/login/oauth2/google
            authorization-grant-type: authorization_code
            scope: profile,email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
